### ISSUE TITLE
Polyfill?

### ISSUE THREAD

**Issue by amirmohsen** [Hacklone/arraync#1]
Correct me if I'm wrong, but as far as I can tell, there is [no proposal](https://github.com/tc39/proposals) for adding async functions to the array prototype, is there? If that's the case as I suspect, calling this library a polyfill is misleading. Also, editing the prototype of built-in types (such as the Array object) is highly discouraged these days as it risks clashes with future standards and other libraries. I suggest you change your library so it uses a new custom array type instead of adding extra methods to the prototype of the native Array. Here's an example using the ES2015 class syntax:

```js
class AsyncArray extends Array {

    constructor(…args) { super(…args); } // Apparently, this super call is necessary for built-in types

    // Your extra async functions
}
```

**Comment by Hacklone** [comment]
Hey,

Yes the calling it polyfill can be misleading (any suggestions what to call this so that it's obvious that it extends the Array's prototype?) but I made sure that this lib doesn't override anything on the Array's prototype. 

Creating a custom Array type is fine but the problem is that it's not convenient at all - nobody would start creating AsyncArrays instead of just ```[]``` and the whole idea for this lib was to make it easy for us to handle async operations on arrays.

Thanks,
Barna

**Comment by amirmohsen** [comment]
Could you at least please include a note in the readme to make it clear that there's no proposal for async operations on the native array type and what you're doing is non-standard? I don't really care about how you do your own projects, but I am afraid this might lead other developers into thinking that you're just polyfilling a future standard which is clearly not the case.

**Comment by Hacklone** [comment]
You're right, I've updated the README
